name: cut_my_garden
description: Flutter Project from ITCoderz using Flutter SDK version 3.10.5 .

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  easy_sidemenu: ^0.4.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  google_maps_flutter_web: ^0.5.0+1
  google_maps_flutter: ^2.3.1
  data_table_2: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/dashboard/
    - assets/images/
    - assets/fonts/inter/
    - assets/fonts/

       
  
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf

