name: cut_my_garden
description: Flutter Project from ITCoderz using Flutter SDK version 3.10.5 .

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  dropdown_button2: ^2.3.6
  google_maps_flutter_web: ^0.5.2
  google_maps_flutter: ^2.3.1
  data_table_2: ^2.5.5
  get: ^4.6.5
  flutter_rating_bar: ^4.0.1
  d_chart: ^2.3.0
  syncfusion_flutter_charts: ^22.1.39
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/dashboard/
    - assets/images/
    - assets/fonts/inter/
    - assets/fonts/

       
  
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf

